In [40]:
import pandas as pd

root = '/home/tristan/Desktop/Repos/DreamHF'

pheno_df_train = pd.read_csv(root + "/train/pheno_training.csv")

df = pheno_df_train
df = df.convert_dtypes()
df = df.astype({'Smoking': 'category', 'PrevalentCHD': 'category', 'BPTreatment': 'category', 'PrevalentDiabetes': 'category', 'PrevalentHFAIL': 'category',
               'Sex': 'category'})

In [42]:
df

,Unnamed: 0,Age,BodyMassIndex,Smoking,BPTreatment,PrevalentDiabetes,PrevalentCHD,PrevalentHFAIL,Event,Event_time,SystolicBP,NonHDLcholesterol,Sex
0,Simulated_328,53.618,24.127,0,0,0,0,0,0,15.75,133.077,3.02,0
1,Simulated_1644,36.811,27.992,0,0,0,0,0,0,15.881,108.914,5.48,0
2,Simulated_1710,49.429,23.664,0,0,0,0,0,0,15.891,110.064,4.388,1
3,Simulated_1732,48.842,26.804,0,0,0,0,0,0,15.918,128.059,5.119,0
4,Simulated_1727,60.738,29.862,0,0,0,0,0,0,15.841,169.913,5.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3610,Simulated_1783,33.802,37.049,0,0,0,0,0,0,15.942,109.08,3.141,0
3611,Simulated_3425,69.249,36.8,0,0,1,0,0,0,15.781,145.953,5.478,1
3612,Simulated_1789,28.561,26.463,0,0,0,0,0,0,12.198,124.091,4.87,1
3613,Simulated_1592,70.278,31.945,0,1,0,0,0,0,15.609,142.038,2.492,0
3614,Simulated_1731,38.799,25.928,0,0,0,0,0,0,15.739,176.939,4.19,0

In [43]:
id = df['Smoking'].isnull()

In [44]:
id.sum()

16

In [45]:
df.dtypes

Unnamed: 0             string
Age                   Float64
BodyMassIndex         Float64
Smoking              category
BPTreatment          category
PrevalentDiabetes    category
PrevalentCHD         category
PrevalentHFAIL       category
Event                   Int64
Event_time            Float64
SystolicBP            Float64
NonHDLcholesterol     Float64
Sex                  category
dtype: object

In [46]:
df = df.astype({'Smoking': 'bool'})

In [47]:
df

,Unnamed: 0,Age,BodyMassIndex,Smoking,BPTreatment,PrevalentDiabetes,PrevalentCHD,PrevalentHFAIL,Event,Event_time,SystolicBP,NonHDLcholesterol,Sex
0,Simulated_328,53.618,24.127,False,0,0,0,0,0,15.75,133.077,3.02,0
1,Simulated_1644,36.811,27.992,False,0,0,0,0,0,15.881,108.914,5.48,0
2,Simulated_1710,49.429,23.664,False,0,0,0,0,0,15.891,110.064,4.388,1
3,Simulated_1732,48.842,26.804,False,0,0,0,0,0,15.918,128.059,5.119,0
4,Simulated_1727,60.738,29.862,False,0,0,0,0,0,15.841,169.913,5.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3610,Simulated_1783,33.802,37.049,False,0,0,0,0,0,15.942,109.08,3.141,0
3611,Simulated_3425,69.249,36.8,False,0,1,0,0,0,15.781,145.953,5.478,1
3612,Simulated_1789,28.561,26.463,False,0,0,0,0,0,12.198,124.091,4.87,1
3613,Simulated_1592,70.278,31.945,False,1,0,0,0,0,15.609,142.038,2.492,0
3614,Simulated_1731,38.799,25.928,False,0,0,0,0,0,15.739,176.939,4.19,0

In [48]:
df.dtypes

Unnamed: 0             string
Age                   Float64
BodyMassIndex         Float64
Smoking                object
BPTreatment          category
PrevalentDiabetes    category
PrevalentCHD         category
PrevalentHFAIL       category
Event                   Int64
Event_time            Float64
SystolicBP            Float64
NonHDLcholesterol     Float64
Sex                  category
dtype: object

In [49]:
df[id]

,Unnamed: 0,Age,BodyMassIndex,Smoking,BPTreatment,PrevalentDiabetes,PrevalentCHD,PrevalentHFAIL,Event,Event_time,SystolicBP,NonHDLcholesterol,Sex
61,Simulated_1338,55.991,36.779,<NA>,0,0,0,0,1,15.821,117.944,4.359,0
69,Simulated_1616,55.978,28.089,<NA>,0,0,0,0,0,14.501,120.971,5.859,1
255,Simulated_1459,57.282,24.293,<NA>,0,0,0,0,0,15.919,149.067,4.458,0
556,Simulated_4788,33.218,22.446,<NA>,0,0,0,0,0,15.928,118.09,5.95,0
653,Simulated_6718,25.072,30.996,<NA>,0,0,0,0,0,15.882,117.035,5.97,1
897,Simulated_7004,43.269,32.913,<NA>,0,0,0,0,0,15.87,129.944,4.678,1
908,Simulated_4798,51.829,24.767,<NA>,0,0,0,0,0,15.841,130.914,3.638,0
973,Simulated_4613,52.058,23.498,<NA>,0,0,0,0,0,15.881,124.929,4.119,0
1099,Simulated_7053,38.999,21.657,<NA>,0,0,0,0,0,15.832,104.936,3.199,0
2075,Simulated_3992,37.319,22.322,<NA>,0,0,0,1,0,-15.85,126.929,3.539,1
2132,Simulated_239,29.622,28.145,<NA>,1,0,0,0,0,15.839,123.055,2.781,0
2658,Simulated_6451,63.92,23.475,<NA>,0,0,0,0,1,15.829,197.044,3.441,1
3375,Simulated_933,25.868,20.152,<NA>,0,0,0,0,0,15.932,124.075,4.432,1
3407,Simulated_3642,64.96,29.014,<NA>,1,0,0,0,0,5.818,149.09,3.049,0
3485,Simulated_1302,49.438,29.576,<NA>,0,0,0,0,0,15.818,131.018,3.78,1
3565,Simulated_3517,65.361,23.76,<NA>,1,0,0,0,0,15.832,137.973,3.299,0

In [50]:
df

,Unnamed: 0,Age,BodyMassIndex,Smoking,BPTreatment,PrevalentDiabetes,PrevalentCHD,PrevalentHFAIL,Event,Event_time,SystolicBP,NonHDLcholesterol,Sex
0,Simulated_328,53.618,24.127,False,0,0,0,0,0,15.75,133.077,3.02,0
1,Simulated_1644,36.811,27.992,False,0,0,0,0,0,15.881,108.914,5.48,0
2,Simulated_1710,49.429,23.664,False,0,0,0,0,0,15.891,110.064,4.388,1
3,Simulated_1732,48.842,26.804,False,0,0,0,0,0,15.918,128.059,5.119,0
4,Simulated_1727,60.738,29.862,False,0,0,0,0,0,15.841,169.913,5.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3610,Simulated_1783,33.802,37.049,False,0,0,0,0,0,15.942,109.08,3.141,0
3611,Simulated_3425,69.249,36.8,False,0,1,0,0,0,15.781,145.953,5.478,1
3612,Simulated_1789,28.561,26.463,False,0,0,0,0,0,12.198,124.091,4.87,1
3613,Simulated_1592,70.278,31.945,False,1,0,0,0,0,15.609,142.038,2.492,0
3614,Simulated_1731,38.799,25.928,False,0,0,0,0,0,15.739,176.939,4.19,0

In [51]:
df.dtypes

Unnamed: 0             string
Age                   Float64
BodyMassIndex         Float64
Smoking                object
BPTreatment          category
PrevalentDiabetes    category
PrevalentCHD         category
PrevalentHFAIL       category
Event                   Int64
Event_time            Float64
SystolicBP            Float64
NonHDLcholesterol     Float64
Sex                  category
dtype: object

## Another solution

In [4]:
import pandas as pd

root = '/home/tristan/Desktop/Repos/DreamHF'

pheno_df_train = pd.read_csv(root + "/train/pheno_training.csv")

df = pheno_df_train
df = df.convert_dtypes()

In [8]:
from sksurv.column import encode_categorical

df = encode_categorical(df, columns= ['Smoking', 'PrevalentCHD', 'BPTreatment', 'PrevalentDiabetes', 'PrevalentHFAIL','Sex'])

/home/tristan/anaconda3/envs/DreamChallenge/lib/python3.10/site-packages/sksurv/column.py:142: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for name, series in table.iteritems():

In [9]:
df

          Unnamed: 0     Age  ...  NonHDLcholesterol  Sex=1
0      Simulated_328  53.618  ...               3.02    0.0
1     Simulated_1644  36.811  ...               5.48    0.0
2     Simulated_1710  49.429  ...              4.388    1.0
3     Simulated_1732  48.842  ...              5.119    0.0
4     Simulated_1727  60.738  ...               5.74    1.0
...              ...     ...  ...                ...    ...
3610  Simulated_1783  33.802  ...              3.141    0.0
3611  Simulated_3425  69.249  ...              5.478    1.0
3612  Simulated_1789  28.561  ...               4.87    1.0
3613  Simulated_1592  70.278  ...              2.492    0.0
3614  Simulated_1731  38.799  ...               4.19    0.0

[3615 rows x 13 columns]

In [11]:
df.dtypes

Unnamed: 0              string
Age                    Float64
BodyMassIndex          Float64
Smoking=1              float64
BPTreatment=1          float64
PrevalentDiabetes=1    float64
PrevalentCHD=1         float64
PrevalentHFAIL=1       float64
Event                    Int64
Event_time             Float64
SystolicBP             Float64
NonHDLcholesterol      Float64
Sex=1                  float64
dtype: object